#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SingleCircuitProgServer "circuits/hamming/HammingDistance_900_old.bmec" 1000 1>results/hammingserverout_old 2>results/hammingservererr_old &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SingleCircuitProgClient "circuits/hamming/HammingDistance_900_old.bmec" 1000 1>results/hammingclientout_old 2>results/hammingclienterr_old & 