#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.PresentServer 1>results/presentserverout 2>results/presentservererr &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.PresentClient 1>results/presentclientout 2>results/presentclienterr & 