#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SetMinimumServerB 1>results/setminimumbserverout 2>results/setminimumbservererr &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SetMinimumClientB 1>results/setminimumbclientout 2>results/setminimumbclienterr & 