#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SetMinimumServerC 1>results/setminimumcserverout 2>results/setminimumcservererr &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SetMinimumClientC 1>results/setminimumcclientout 2>results/setminimumcclienterr & 