#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.AESServer false 1000 1>results/aesserverout_old 2>results/aesservererr_old &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.AESClient false 1000 1>results/aesclientout_old 2>results/aesclienterr_old & 