#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SingleCircuitProgServer "circuits/fastMultiplication/FMUL_128_128.bmec" 1000 1>results/fastmulserverout 2>results/fastmulservererr &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SingleCircuitProgClient "circuits/fastMultiplication/FMUL_128_128.bmec" 1000 1>results/fastmulclientout 2>results/fastmulclienterr & 