#!/bin/bash

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SingleCircuitProgServer "circuits/hamming/HammingDistance_900.bmec" 1000 1>results/hammingserverout 2>results/hammingservererr &

sleep 0.8

java -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SingleCircuitProgClient "circuits/hamming/HammingDistance_900.bmec" 1000 1>results/hammingclientout 2>results/hammingclienterr & 