#!/bin/bash

java -Xmx1024m -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SetMinimumServerA 1>results/setminimumaserverout 2>results/setminimumaservererr &

sleep 0.8

java -Xmx1024m -cp dist/ME_SFE.jar:extlibs/commons-io-1.4.jar prog.SetMinimumClientA 1>results/setminimumaclientout 2>results/setminimumaclienterr & 